workflows:
  ios-workflow:
    name: Magic Rain iOS
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.smartapps.magicrain
        certificate_private_key: Encrypted(...)
    scripts:
      - name: Build
        script: echo "GDevelop HTML5 game"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: Codemagic
        key_id: B6RHC26A8M
        issuer_id: 47a4bfd1-7959-4bec-a3d1-09b78eb6abe7
        submit_to_testflight: true