workflows:
  ios-workflow:
    name: Magic Rain iOS
    max_build_duration: 120
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.smartapps.magicrain
    scripts:
      - name: Build
        script: echo "GDevelop HTML5 game"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        submit_to_testflight: true