workflows:
  ios-workflow:
    name: Magic Rain iOS
    max_build_duration: 120
    environment:
      groups:
        - deploy
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.smartapps.magicrain
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/cli @capacitor/core @capacitor/ios
      - name: Build iOS
        script: node_modules/.bin/cap sync ios
      - name: Set Xcode project signing
        script: |
          cd ios/App
          xcode-project use-profiles
      - name: Xcode build
        script: |
          cd ios/App
          sed -i '' "1i\\
          install! 'cocoapods', :disable_input_output_paths => true\\
          " Podfile
          pod install
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath ../../build/App.xcarchive archive
      - name: Export IPA
        script: |
          cd ios/App
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.smartapps.magicrain</key>
              <string>Codemagic</string>
            </dict>
          </dict>
          </plist>' > ExportOptions.plist
          xcodebuild -exportArchive -archivePath ../../build/App.xcarchive -exportPath ../../build/ios/ipa -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: key_id
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: B6RHC26A8M
        issuer_id: 47a4bfd1-7959-4bec-a3d1-09b78eb6abe7
        submit_to_testflight: true